services:
  billing-server:
    build:
      context: .
    container_name: billing-server
    ports:
      - "8081:8081"
    depends_on:
      billing-db:
        condition: service_started
      rabbitmq:
          condition: service_healthy
    restart: unless-stopped
    volumes:
      - billing_storage:/app/storage
    networks:
      - ms-net
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  billing-db:
    image: postgres:18
    container_name: billing-db
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ms-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    restart: unless-stopped
    networks:
      - ms-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  billing_db_data:
  billing_storage:

networks:
  ms-net:
    external: true