services:
  billing-server:
    build:
      context: .
    container_name: billing-server
    ports:
      - "8081:8081"
    depends_on:
      - billing-db
    restart: unless-stopped
    volumes:
      - billing_storage:/app/storage
    networks:
      - ms-net
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888

  billing-db:
    image: postgres:18
    container_name: billing-db
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ms-net

volumes:
  billing_db_data:
  billing_storage:

networks:
  ms-net:
    external: true