spring.application.name=billing-service
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_service_db
spring.datasource.username=postgres
spring.datasource.password=Mes2021**
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

#flyway settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=false