package com.example.billingservice.domain.enums;

public enum InvoiceEventType {
    CREATED,
    UPDATED,
    STATUS_CHANGED,
    PAYMENT_REGISTERED,
    PAYMENT_METHOD_UPDATED,
    CANCELLED,
    DOCUMENT_ATTACHED,
    DOCUMENT_VALIDATED,
    SIGNATURE_REQUESTED,
    SIGNATURE_SUCCEEDED,
    SIGNATURE_FAILED,
    TTN_SUBMISSION_REQUESTED,
    TTN_SUBMITTED,
    TTN_ACCEPTED,
    TTN_REJECTED,
    FX_RATE_APPLIED
}
